### PR TITLE
adding new flag '-t --templates'

### PR DESCRIPTION
**Pull request by gulien**
Adds the new flag `-t --templates` which allows to bring additional templates in the "main" template.

### CODE REVIEW

**Comment by gulien** [comment]
@andrewebdev is it ok for your case?

**Comment by andrewebdev** [comment]
Aye this looks like it will work perfectly. Should allow to re-use snippets rather than hand writing/maintaining them for multiple templates.

PS: That was a really fast turn-around. Didn't expect that :)

**Comment by gulien** [comment]
Great :)

Yeah I fill the time gap between world cup games ⚽️

**Comment by gulien** [comment]
Fixes #33

**Pull request merged**
